services:
  geoserver:
    image: kartoza/geoserver:latest
    container_name: vital-watch-geoserver
    ports:
      - "8080:8080"
    environment:
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - ./rasters:/opt/geoserver/rasters:ro
    restart: unless-stopped

volumes:
  geoserver_data:
